version: '3'
services:
  slack-time-cmd:
    build: .
    image: registry.heroku.com/slack-time-cmd/web
    environment:
      - PORT
      - SLACK_OAUTH_TOKEN
    ports:
      - "1234:1234"
  db:
    image: postgres:11.4-alpine
    environment:
      - POSTGRES_DB=slack_time_cmd
    ports:
     - "5432:5432"
